name: deploy-react
on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy RoadMapKU Frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/RoadMapKU

            # 기존 프로세스 종료
            pid=$(lsof -t -i:3000)
            if [ ! -z "$pid" ]; then
              echo "Killing process on port 3000..."
              kill -9 $pid || true
            fi

            # 소스 업데이트
            git fetch origin develop
            git reset --hard origin/develop

            # Docker 이미지 재생성 및 실행
            docker-compose down
            docker-compose up -d --build
