name: deploy-react
on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(master)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/RoadMapKU

            # 환경 정보 출력
            echo "Current directory: $(pwd)"
            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"
            echo "Yarn version: $(yarn -v)"

            git add .
            git commit -m "temp"
            git fetch origin develop
            git merge origin/develop

            yarn install
            yarn build

            # build 디렉토리 확인
            echo "Build directory contents:"
            ls -la build/

            PORT=3000
            echo "Starting serve on port $PORT..."
            serve -s build -l $PORT >> output.log 2>&1 &

            # 상세한 프로세스 정보 출력
            sleep 5
            echo "Process info:"
            ps aux | grep serve

            echo "Port usage:"
            netstat -tulpn | grep :3000

            echo "Log contents:"
            tail -n 50 output.log
