name: deploy-react
on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(master)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/RoadMapKU

           # 1. 기존 3000 포트 프로세스 종료
            sudo kill -9 $(sudo lsof -t -i:3000) || true
            
            # 2. git 작업
            git add .
            git commit -m "temp" || true
            git fetch origin develop
            git merge origin/develop
            
            # 3. 빌드
            yarn install
            yarn build
            
            # 5. 새로운 포트(3001)로 실행
            PORT=3000
            echo "Starting serve on port $PORT..."
            nohup serve -s build -l $PORT >> output.log 2>&1 &
            
            # 6. 프로세스 확인
            sleep 5
            if pgrep -f "serve -s build" > /dev/null; then
              echo "Serve process is running successfully"
              ps aux | grep serve
            else
              echo "Failed to start serve process"
              cat output.log
              exit 1
            fi
