name: deploy-react
on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(master)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/RoadMapKU
            git add .
            git commit -m "temp"
            git fetch origin develop
            git merge origin/develop
            nohup yarn start >> output.log 2>&1 &
