name: deploy-react
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy spring MainServer(master)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/RoadMapKU

            # 기존 프로세스 종료 (sudo 없이)
            pid=$(lsof -t -i:3000)
            if [ ! -z "$pid" ]; then
              echo "Killing process on port 3000..."
              kill -9 $pid || true
            fi

            # git 작업
            git add .
            git commit -m "temp" || true
            git fetch origin develop
            git merge origin/develop

            yarn install
            yarn build
